name: finance

services:
  swagger:
    build: swagger-ui
    image: swagger-finance:1.0.0
    ports:
      - 81:8080
    networks:
      - finance-network
  pg_db:
    build: postgresql
    image: postgresql-finance:1.0.1
    environment:
      POSTGRES_USER: finance_admin
      POSTGRES_PASSWORD: 123
    networks:
      - finance-network
  pgadmin:
    build: pgadmin
    image: pgadmin-finance:1.0.0
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@finance.com
      PGADMIN_DEFAULT_PASSWORD: finance
    ports:
      - 82:80
    networks:
      - finance-network
  user-service:
    build: user-service
    image: user-service-finance:1.0.4
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: 'jdbc:postgresql://pg_db:5432/user_service?currentSchema=data'
      DB_USER: user_service_user
      DB_PASSWORD: 'ZF3w{&M1;1_\'
    networks:
      - finance-network
  audit-service:
    build: audit-service
    image: audit-service-finance:1.0.0
    networks:
      - finance-network
  proxy:
    build: proxy
    image: proxy-finance:1.0.0
    ports:
      - 80:80
    networks:
      - finance-network
networks:
  finance-network: